# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
