# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tenant_id',
            field=models.UUIDField(default='72f988bf-86f1-41af-91ab-2d7cd011db47'),
            preserve_default=False,
        ),
    ]
