# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160720_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='token',
            new_name='ols_token',
        ),
        migrations.AddField(
            model_name='account',
            name='graph_token',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
