# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_person_connections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='id',
            new_name='office_id',
        ),
    ]
