# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20160720_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
