# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20160720_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='id',
            new_name='office_id',
        ),
    ]
